name: 'Curso_data_engineering'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  Curso_data_engineering:
    staging:
      +database: DB31_SILVER_DB
      +materialized: view

    marts:
      +database: DB31_GOLD_DB
      +materialized: table
